#apps/backend/modules/product/config/generator.yml
generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TiresProduct
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tires_product
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~

      fields:
#        Що і як показувати
        fotoname: { label: Foto}
#        page_products_count: { label: шт/стр ?}
      list:
      #      Заголовак для списку
        title: Admin Product Management
      #         Які поля показуємо і що буде посиланням
        display:    [fotoname,=name, price, category, active]
      #         Первинне сортування
        sort: [name, desc]
      #         Відміняємо групові операції
#        batch_actions: {}
      #         Для пагінатора TO DO
        max_per_page: 10

#        table_method: retrieveBackendJobList

      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
