<?php

/**
 * TiresCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TiresCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TiresCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TiresCategory');
    }
}