<?php

/**
 * TiresAttributeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TiresAttributeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TiresAttributeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TiresAttribute');
    }
}