<?php

/**
 * TiresValuesetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TiresValuesetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TiresValuesetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TiresValueset');
    }
}