<?php

/**
 * TiresCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    tires
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TiresCategory extends BaseTiresCategory
{
    public function getOnlyActiveCategory()
    {
        $q = $this->createQuery('j')
            ->where('j.active = ?', true); //TO DO

        return $q->execute();
    }
    public function getActiveProductsQuery()
    {
        $q = Doctrine_Query::create()
            ->from('TiresProduct j')
            ->where('j.uidd_category = ?', $this->getUuid());

        return Doctrine::getTable('TiresProduct')->addActiveProductsQuery($q);
    }

    public function getActiveProducts($max = 10)
    {
        $q = $this->getActiveProductsQuery()
            ->limit($max);

        return $q->execute();
    }

    public function countActiveProducts()
    {
        return $this->getActiveProductsQuery()->count();
    }
}