<?php

/**
 * TiresGoodmenuTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TiresGoodmenuTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TiresGoodmenuTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TiresGoodmenu');
    }

}