<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/08/15 19:05:28

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=tires',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
