<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/09/01 21:29:22

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=tires',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
