<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/09/02 01:08:06

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=tires',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
