
detect_relations: true
options:
  charset: utf8
  type: InnoDB

TiresAttribute:
  tableName: Tires_attribute
  actAs:
    Sluggable:
      fields: [name]
  columns:
    name:
      type: string(255)
      notnull:  true
    uuid:
      type: integer(8)
      primary: true
      notnull: true
      autoincrement: true
    uuid_category:
      type: integer(8)
      notnull: true
#      default: '0'
    multiple_choice:
      type: boolean
      default: '1'
  relations:
    TiresCategory:
      class: TiresCategory
      local: uuid_category
      foreign: uuid
      foreignAlias: TiresAttributes
      onDelete: cascade
      foreignType: many
      owningSide: true
  indexes:
    uuid_category_idx:
      fields: [uuid_category]
  options:
    charset: utf8

TiresValueset:
  tableName: Tires_valueset
  columns:
    uuid:
      type: integer(8)
      primary: true
      notnull: true
      autoincrement: true
    products_uuid:
      type: integer(8)
#      default: '0'
    attributes_uuid:
      type: integer(8)
#      default: '0'
    value:
      type: string(255)
      default: null
  relations:
    TiresAttribute:
      class: TiresAttribute
      local: attributes_uuid
      foreign: uuid
      foreignAlias: TiresValuesets
#      onDelete: cascade
#      onUpdate: restrict
      foreignType: many
      owningSide: true
    TiresProduct:
      class: TiresProduct
      local: products_uuid
      foreign: uuid
      foreignAlias: TiresValuesets
      foreignType: many
      owningSide: true
  indexes:
    fk_products1_idx_idx_idx_idx:
      fields: [products_uuid]
    fk_attribut1_idx_idx_idx_idx:
      fields: [attributes_uuid]
  options:
    charset: utf8

TiresCategory:
  tableName: Tires_category
  actAs:
    Sluggable:
      fields: [name]
  columns:
    uuid:
      type: integer(8)
      primary: true
      notnull: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true
    active:
      type: boolean
      default: '1'
    page_products_count:
      type: integer(4)
      default: '10'
    fotoname:
      type: string(255)
      notnull: true
  options:
    charset: utf8

TiresProduct:
  tableName: Tires_product
  actAs:
    Sluggable:
      fields: [name]
  columns:
    uuid:
      type: integer(8)
      primary: true
      notnull: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true
    uuid_category:
      type: integer(8)
      notnull: true
#      default: '0'
    price:
      type: decimal(11)
      scale: 4
      default: null
    active:
      type: boolean
      default: '1'
    fotoname:
      type: string(255)
      notnull: true
  relations:
    TiresCategory:
      class: TiresCategory
      local: uuid_category
      foreign: uuid
      foreignAlias: TiresProducts
      onDelete: cascade
      onUpdate: restrict
      foreignType: many
      owningSide: true
  indexes:
    uuid_category_idx_idx_idx_idx:
      fields: [uuid_category]
  options:
    charset: utf8

TiresGoodmenu:
  tableName: Tires_goodmenu
  actAs:
    NestedSet:
      hasManyRoots: true
      rootColumnName: root_id
  columns:
    uuid:
      type: integer(20)
      primary: true
      notnull: true
      autoincrement: true
    reference:
      type: string(255)
#      unique: true
      default: null
    name:
      type: string(255)
      default: null
    level:
      type: integer(4)
      default: null
  options:
    charset: utf8
